# Generated by Django 3.2.5 on 2021-11-26 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('className', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=50)),
                ('teacher', models.EmailField(max_length=100)),
                ('classTeacherMail', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('submissionDate', models.DateField()),
                ('assignmentCode', models.CharField(max_length=10)),
                ('attachments', models.FileField(blank=True, max_length=200, upload_to='')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('teacherEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('classTeacherMail', models.ManyToManyField(to='classRoom.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('studentEmail', models.EmailField(max_length=254)),
                ('attachments', models.FileField(max_length=200, upload_to='')),
                ('submissionDate', models.DateField(default=datetime.date.today)),
                ('comment', models.TextField(null=True)),
                ('studentEmailAssignmentCode', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.createassignment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('studentEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('classTeacherMail', models.ManyToManyField(to='classRoom.Classroom')),
            ],
        ),
    ]
