# Generated by Django 3.2.5 on 2021-11-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0005_alter_submitassignment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='pinned',
        ),
        migrations.AddField(
            model_name='createassignment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
