# Generated by Django 3.2.5 on 2022-03-12 08:02

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0009_alter_submitassignment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('videoCode', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.classroom')),
            ],
        ),
    ]
