# Generated by Django 3.2.5 on 2022-05-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0011_videotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('videoCode', models.CharField(max_length=10)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('excelPath', models.TextField(null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classRoom.classroom')),
            ],
        ),
    ]
