# Generated by Django 3.2.5 on 2022-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0012_lectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
