# Generated by Django 3.2.5 on 2022-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0015_auto_20220515_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='excelFilePath',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
