# Generated by Django 3.2.5 on 2022-05-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0018_createquiz_quizcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createquiz',
            old_name='submissionDate',
            new_name='quizDate',
        ),
    ]
