# Generated by Django 3.2.5 on 2021-11-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0003_alter_submitassignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassignment',
            name='comment',
            field=models.TextField(default='No Comments'),
        ),
    ]
