# Generated by Django 3.2.5 on 2021-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0006_auto_20211127_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createassignment',
            name='pinned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
