# Generated by Django 3.2.5 on 2021-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0007_alter_createassignment_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='createassignment',
            name='resource',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
