# Generated by Django 3.2.5 on 2021-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoom', '0008_createassignment_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassignment',
            name='comment',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
